version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: elasticsearch
    restart: always
    read_only: true
    environment:
      - TZ=Europe/Berlin
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esconfig:/usr/share/elasticsearch/config
      - eslogs:/usr/share/elasticsearch/logs
    tmpfs:
      - /tmp:exec,mode=1777
    healthcheck:
      test: ["CMD", "curl", "--fail", "--noproxy", "localhost", "http://localhost:9200/"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - 9200:9200
#      - 9300:9300
    networks:
      - elastic-net

#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.11.2
#    container_name: kibana
#    ports:
#      - 5601:5601
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
#    networks:
#      - elastic-net

volumes:
  esdata:
    driver: local
  esconfig:
    driver: local
  eslogs:
    driver: local

networks:
  elastic-net:
    driver: bridge
    name: elastic-net