services:

  mongodb:
    mem_limit: 128m
    image: mongo:6.0.4
    container_name: dev-mongodb
    restart: 'no'
    ports:
      - 27017:27017
    volumes:
      - mongoconfig:/data/configdb
      - mongodata:/data/db
    environment:
      TZ: "Europe/Berlin"
      MONGO_INITDB_ROOT_USERNAME: "mongodb"
      MONGO_INITDB_ROOT_PASSWORD: "mongodb"

volumes:
  mongoconfig:
  mongodata:
  pgdata: