server:
  port: 50800
  tomcat.threads.max: 20

## actuator section
management:
    endpoints:
      web:
        exposure:
          include: "info,health,heapdump,prometheus"
    endpoint:
      health:
        show-details: always

#persistence
database.provisioning.goals: "-import-demo-data"

spring:
  data:
    #mongodb
    mongodb:
      port: 27017
      host: localhost
      authentication-database: admin
      database: search
      username: mongodb
      password: mongodb

  elasticsearch:

    uris:
      - http://localhost:9200


#activate mongodb or elasticsearch by excluding the other
elastic.configuration: "org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration, org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration, org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration"
mongodb.configuration: "org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration"

spring.autoconfigure.exclude: ${mongodb.configuration}

#graphql
spring.graphql.graphiql.enabled: "true"
spring.graphql.graphiql.path: "/graphiql"

#log levels
logging.level.root: "WARN"
logging.level.org.goafabric: "INFO"

logging.level.org.springframework: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "DEBUG"

