server:
  port: 50800
  tomcat.threads.max: 20

## actuator section
management:
    endpoints:
      web:
        exposure:
          include: "info,health,heapdump,prometheus"
    endpoint:
      health:
        show-details: always

#persistence
database.provisioning.goals: "-import-demo-data"

#mongo
spring.data.mongodb.uri: "mongodb://mongodb:mongodb@localhost:27017/person?authSource=admin"
de.flapdoodle.mongodb.embedded.version: 7.0.9

#elastic
spring.elasticsearch.uris: "http://localhost:9200"
management.health.elasticsearch.enabled: false

#profile, we append "." to not exclude a specific autoconfiguration to select the database
spring.autoconfigure.exclude:
  ${mongodb.autoconfiguration},${elasticsearch.autoconfiguration.},${redis.autoconfiguration} #${opensearch.autoconfiguration.inverse}

mongodb.autoconfiguration: "org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration"
elasticsearch.autoconfiguration: "org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration, org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration, org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration"
redis.autoconfiguration: "org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration, org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration"
opensearch.autoconfiguration.inverse: "org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration"

#graphql
spring.graphql.graphiql.enabled: "true"
spring.graphql.graphiql.path: "/graphiql"

#log levels
logging.level.root: "WARN"
logging.level.org.goafabric: "INFO"

logging.level.org.springframework: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "DEBUG"

